### ISSUE TITLE
Бачу, що ексепшений створюються і кидаються, але де вони ловляться?

### ISSUE THREAD

**Issue by soulcub** [fru2zzy/Playtika#2]
https://github.com/fru2zzy/Playtika/blob/71cd2261af6212160eeb1034708fa00afc2d7a4f/src/FailSearchEngine.java#L13

Суть не просто в тому, щоб кидати, але ще і у тому, щоб не дати програмі впасти через ексепшн. Потрібно додати обробку

**Comment by fru2zzy** [comment]
Done, now catching and processing in the Main class
